### ISSUE TITLE
Hi, do you have any intention to make the work public.

### ISSUE THREAD

**Issue by JinLong-Qin** [Yzmblog/SurfD#1]
Very excellent work. I would like to ask you if you intend to make the code and data open.

**Comment by Bathsheba** [comment]
this

**Comment by JinLong-Qin** [comment]
> this

what do you mean?

**Comment by Yzmblog** [comment]
Hi, thanks for your attention. Yes, we are cleaning the codes now, and will public the codes as soon as possible. Thanks!

**Comment by sunshineatnoon** [comment]
Hi @Yzmblog Awesome work, do you have a release date in mind? Looking forward to the code

**Comment by songwei100110** [comment]
1

**Comment by Bathsheba** [comment]
well that was disappointing

**Comment by icegaomu** [comment]
Very excellent work.  Do you have a specific timeline for releasing the code?

**Comment by Yzmblog** [comment]
Hi, Sorry for the long delay. The codes are now open. Thank you all for your interest~ 😀
