### ISSUE TITLE
grad_loss loss occur in custom dataset

### ISSUE THREAD

**Issue by jxxtin** [Yzmblog/SurfD#3]
There are instances where nan appears in grad_loss in a custom dataset.

What could be causing this issue?

**Comment by Yzmblog** [comment]
Hi, Do you center normalize the object to 0-1 first? I don't know what kind of data you use, please first check if the preprocess is correct.

**Comment by jxxtin** [comment]
Thanks for your suggestion

Since I'm newbie in the 3D domain, I didn't know much about 3D

I can solved it well using center normalize.

Thanks a lot!!
