### ISSUE TITLE
About Pix3D datasets preprocess~~   

### ISSUE THREAD

**Issue by LeeCASC** [Yzmblog/SurfD#6]
Before using preprocess_udfs.py to process Pix3D, you have already divided the original Pix3D dataset into train, test and done some other processing. Can you provide a more detailed preprocessing script about Pix3D?
Thank you very much~~

**Comment by Yzmblog** [comment]
Hi, Yes, we first divide it to train and test according to the original pix3d dataset. Which can be found here: https://github.com/xingyuansun/pix3d/tree/master/eval/list

**Comment by LeeCASC** [comment]
Thanks~~

**Comment by FeiiYin** [comment]
Hi, sorry to bother. I just checked the link you provided `https://github.com/xingyuansun/pix3d/tree/master/eval/list`. It seems the original repo only provide the devision of chair category. Can u provide some hints or share some scripts about the rest categories? That would be very helpful to me! Thanks in advance.

Best

**Comment by Yzmblog** [comment]
> Hi, sorry to bother. I just checked the link you provided `https://github.com/xingyuansun/pix3d/tree/master/eval/list`. It seems the original repo only provide the devision of chair category. Can u provide some hints or share some scripts about the rest categories? That would be very helpful to me! Thanks in advance.
> 
> Best

Hi, sorry for the late reply! I just updated the train and test split txt file at [pix3d](https://github.com/Yzmblog/SurfD/tree/main/AutoEncoder/dataset_info_files/Pix3d), please check it out.

**Comment by FeiiYin** [comment]
Thx! It really helps. 

By the way, may I further ask another question, why the model selects UDF instead of SDF for learning? Is UDF more easy to learn?

**Comment by Yzmblog** [comment]
> Thx! It really helps.
> 
> By the way, may I further ask another question, why the model selects UDF instead of SDF for learning? Is UDF more easy to learn?

That's a good question. The main reason is UDF can represent non-watertight objects(like clothes, open surfaces,  complex topology objects, etc...) which SDF cannot do. And for the learning part, UDF is actually more difficult to learn due to the non-differentiable property at the zero point.

**Comment by FeiiYin** [comment]
Thx! It really helps. Hope you can publish more works in the future~

**Comment by Yzmblog** [comment]
> Thx! It really helps. Hope you can publish more works in the future~

Thanks for the kind words! Glad to discuss with you!
